### ISSUE TITLE
Validate on Mac OS

### ISSUE THREAD

**Issue by gregkrsak** [gregkrsak/phase-deuce#2]
Basic functionality has been verified on Linux, but not on Mac OS.

Please check to ensure the app works, and generates at lease one properly formatted log file.

**Comment by shawndowling** [comment]
Confirmed that base functionality is working on macOS using Python 3.7 installed via brew.

Here is a snippet of the log file produced:

`589431901,Kimberly Garcia,kimberlygarcia@aol.com,450-551-5374,981603008`

**Comment by gregkrsak** [comment]
Thanks dude!
