### ISSUE TITLE
Add Python installation instructions to README

### ISSUE THREAD

**Issue by gregkrsak** [gregkrsak/phase-deuce#7]

**Comment by CodeSadhu** [comment]
Just add Python installation instructions to the README? If nobody's assigned, I'd like to take it up!

**Comment by gregkrsak** [comment]
Go for it!

**Comment by gregkrsak** [comment]
Pull request this into the staging branch whenever you're ready

**Comment by CodeSadhu** [comment]
@gregkrsak PR sent
